### ISSUE TITLE
Direct Challenges don't work

### ISSUE THREAD

**Issue by Erisa** [WakingStones/CallersBane-Issues#4]
**Describe the bug**
Sending direct challenge requests to other players doesn't function, they can't be accepted.

**To Reproduce**
1. Find a player on the chat's online list.
2. Send them a challenge (Right click -> Challenge)
3. Have them try to accept the incoming challenge request
4. The accept button does nothing and the challenge eventually times out

**Expected behavior**
Clicking accept should go to the deck selection, and then proceed with the challenge as normal.

**Server or Client?**
No real way to tell, so I don't actually know for now. I haven't tested on a local server yet.

**Desktop (please complete the following information):**
 - OS: Windows (Havent tested others)

**Comment by AndrewSav** [comment]
Custom matches do not seem to work either

**Comment by Erisa** [comment]
Custom matches work against the AI for me, but not against other players.
